apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdb-manager
  namespace: sre

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pdb-manager-role
rules:
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pdb-manager-binding
subjects:
- kind: ServiceAccount
  name: pdb-manager
  namespace: sre
roleRef:
  kind: ClusterRole
  name: pdb-manager-role
  apiGroup: rbac.authorization.k8s.io
